# Generated by Django 5.0 on 2023-12-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0002_tag_users_alter_task_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
    ]
